return {
	codex_chat_line_highlights = {},
	codex_chat_line_to_buf = {},
	codex_deleted_jobs = {},
	codex_session_order = {},
	codex_sessions = {},
	codex_jobs_line_highlights = {},
	codex_jobs_line_to_id = {},
	active_ephemeral_diagnostics = {},
	ephemeral_jobs = {},
	ephemeral_job_order = {},
	next_ephemeral_job_id = 1,
	next_ephemeral_diagnostic_id = 1,
	next_ephemeral_result_id = 1,
	next_ephemeral_sign_id = 1,
	next_codex_session_id = 1,
	ephemeral_models = {
		command = nil,
		edit = nil,
	},
	setup_done = false,
}
